# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # Delete head branch on merge
  delete_branch_on_merge: true

  # Merge options
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

  # Default to squash merge commit title
  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: PR_BODY
